version: '3'
services:
  app:
    container_name: "node_backend"
    build: .
    ports:
      - "3000:3000"
    links: 
      - postgres
      - prisma
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: '5432'
            database: intagram
            schema: public
            user: postgres
            password: asdqwe123
            migrations: true
  postgres:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "asdqwe123"
      POSTGRES_USER: "postgres"